```c++

float divide(float num1, float num2) {
if (num2 == 0) {
throw 200; // Пробрасываем ошибку
}
return num1 / num2;
}

int main() {
// ... значит поймать любую ошибку
try {
divide(5, 0);
} catch (...) {
cout << "Error";
}

    return 0;
}

```

## Запмните. exception - это базовый класс для всех исключений. Поэтому можно писать catch(exception &e) и ловить все исключения.

Мы всегда пишем свои классы исключений, которые наследуются от exception. Таким образом, мы можем ловить их по типу.

